# Generated by Django 6.0.6 on 2026-06-30 09:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_category', models.CharField(choices=[('HOUSE_PARTY', 'House Party'), ('DINNER_PARTY', 'Dinner Party'), ('GAME_NIGHT', 'Game Night'), ('LIVE_MUSIC', 'Live Music'), ('KARAOKE', 'Karaoke'), ('NETWORKING', 'Networking'), ('BOOK_CLUB', 'Book Club'), ('MOVIE_NIGHT', 'Movie Night'), ('COOKING_CLASS', 'Cooking Class'), ('WELLNESS', 'Wellness'), ('ART_CRAFT', 'Art & Craft'), ('COFFEE_MEETUP', 'Coffee Meetup'), ('CELEBRATION', 'Celebration'), ('DANCE_PARTY', 'Dance Party'), ('WATCH_PARTY', 'Watch Party'), ('CULTURAL_MEETUP', 'Cultural Meetup'), ('WORKSHOP', 'Workshop'), ('OPEN_MIC', 'Open Mic'), ('OTHER', 'Other')], db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='event_posters/')),
                ('max_members', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('ANY', 'Any'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='ANY', max_length=10)),
                ('age_limit', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField(default=datetime.time(22, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
