# Generated by Django 6.0.6 on 2026-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default='No rules specified.'),
            preserve_default=False,
        ),
    ]
