# Generated by Django 6.0.6 on 2026-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
